### ISSUE TITLE
CPP_waitForTriggerDemo crashes

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_PTB#47] opened 2020-07-27 16:10 UTC
CPP_waitForTriggerDemo.m crashes, please see below:
```
>> waitForTrigger(cfg);
Will wait for triggers on the main keyboard device.
Waiting for trigger 
 Trigger 1 
Reference to non-existent field 'MRI'.

Error in waitForTrigger>pauseBetweenTriggers (line 74)
    if ~isempty(cfg.MRI.repetitionTime)

Error in waitForTrigger (line 46)
                    pauseBetweenTriggers(cfg);
```

**Comment by CerenB** [comment] 2020-07-27 16:16
in `CPP_getResponseDemo.m`

I'm using macbook pro, touchbar has esc key and when i try esc as key press, I got this error:
```
Reference to non-existent field 'pressed'.

Error in CPP_getResponseDemo (line 99)
        if responseEvents(iEvent).pressed
```
maybe @marcobarilari can try and replicate the error in his laptop?

**Comment by Remi-Gau** [comment] 2020-07-27 16:40
OK I defo need to remember to run the demos and not just the test.

**Comment by CerenB** [comment] 2020-07-27 18:25
@Remi-Gau where do you set cfg.MRI field? 
`waitForTrigger.m` crashes due to non-existing `cfg.MRI.repetitionTime`

**Comment by CerenB** [comment] 2020-07-27 19:08
as a side note, when do the change from expParam to cfg be careful with such:
```
if nargin < 2
        cfg = struct();
    end
```
They empty your cfg which contains everything.

**Comment by marcobarilari** [comment] 2020-07-27 21:15
> in `CPP_getResponseDemo.m`
> 
> I'm using macbook pro, touchbar has esc key and when i try esc as key press, I got this error:
> 
> ```
> Reference to non-existent field 'pressed'.
> 
> Error in CPP_getResponseDemo (line 99)
>         if responseEvents(iEvent).pressed
> ```
> 
> maybe @marcobarilari can try and replicate the error in his laptop?
> 
> Note: in CPP_checkAbortDemo.m the esc key works, I receive the following:
> 
> ```
> >> CPP_checkAbortDemo
> Warning: You pressed the escape key: will try to fail gracefully. 
> > In CPP_checkAbortDemo (line 24) 
> 
> We did catch your abort signal.
> ```

yep, same error, I guess the problem is that in `getResponse` we have `errorAbortGetReponse(responseEvents);`  while the function itself is 

```matlab
function errorAbortGetReponse

    errorStruct.message = 'Escape key press detected by getResponse: aborting experiment.';
    errorStruct.identifier = 'getResponse:abortRequested';

    error(errorStruct);
end
```

**Comment by CerenB** [comment] 2020-07-27 22:09
oh! that's easy to fix then :)

**Comment by marcobarilari** [comment] 2020-09-30 21:02
@Ceren and @Remi-Gau I think that both the demos mentioned in this issue are working (I say it because I try) so I am going to close this one. 

Reopen it if you test them and they fail.

**Closed by marcobarilari** 2020-09-30 21:02 UTC
Labels: priority 1
